server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:github-pcz/springcloud-config.git   #GitHub上面的git仓库名字
          #搜索目录
          search-paths:
            - springcloud-config    # 仓库的名称
      # 读取分支
      label: mater

  #rabbitmq的相关配置，15672是web管理界面的端口，5672是MQ的访问端口
  rabbitmq:
    host: 192.168.116.129
    port: 5672
    username: guest
    password: guest

# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#rabbitmq的相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
